# Use the official Postgres image
FROM postgres:15

# Set environment variables for DB
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=a
ENV POSTGRES_DB=products_db

# Expose default Postgres port
EXPOSE 5432
