apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
data:
  # base64 encoded values
  POSTGRES_USER: YWRtaW4=        # admin
  POSTGRES_PASSWORD: YWRtaW4xMjM= # admin123
